version: "3"

services:
  # 
  whoami:
    image: jennerwein/whoami:latest
    networks:
      - nginx-proxy
    container_name: "whoami"
    environment:
      VIRTUAL_HOST: whoami.cscld.de
      LETSENCRYPT_HOST: whoami.cscld.de
      LETSENCRYPT_EMAIL: test@cscld.de

networks:
  nginx-proxy:
    external: 
      name: nginx-proxy

